#!/bin/bash
#Joomla test-script
#first bash/shell scripting url
#http://linuxcommand.org/lc3_wss0010.php

#run this to give the shell permissions
#chmod 755 test-script

function test_me () {
  printf "\n my_dir_name b4 = $my_dir_name  \n\n"
  my_dir_name=${1:-'who'}
  printf "\n my_dir_name after = $my_dir_name  \n\n"
} #test_me

#test_me

function tm2 (){
  #test source'd  files access to global scoped script variables
  printf "\n test-script - var test template_url = $template_url"
  #this works souce'd files have access to the variables of the main script
}

printf "***********************************************
 *************** TEST SCRIPT IS RUNING ****************
 *****************************************************"
