#!/bin/bash
#Joomla ultimate-warrior template
#first bash/shell scripting url
#http://linuxcommand.org/lc3_wss0010.php

#run this to give the shell permissions
#chmod 755 ultimate-warrior

  #ask whether we are doing template, zip or both
  #source works like using import or require in js
  source src/print_ef.sh
  source src/user_input.sh
  source src/create_template.sh
  source src/get_path.sh
  source src/get_main.sh
  source src/create_directory.sh
  source src/template_type.sh
  source src/get_directory.sh
  source src/template_title.sh
  source src/get_mode.sh
  source src/prep_output.sh
  source src/replace_xml.sh
  source src/target.sh
  source src/update_names.sh
  source src/zip_files.sh
  # source src/create_package.sh
  source src/get_module_parent.sh
  # source src/create_module.sh


  mode_letter=""
  template_letter=""
  work_mode=""
  template_type=""
  template_location=""
  template_url=""

  temporary_directory="output"
  temp_dir="$temporary_directory"

  # pf "temp_dir = $temp_dir"

  user_mode="dev"

  #/********** COMPONENT VARIABLES **********/
  component_name=""
  cn=""
  cn_caps=""
  cn_init=""
  cn_full=""
  cn_full_caps=""
  my_year=""
  my_month_year=""

  #/********** MODULE VARIABLES *************/
  module_name=""
  module_name=""
  mn_caps=""
  mn_init=""
  mn_full=""
  mn_full_caps=""
  my_year=""
  my_month_year=""
  official_title_mod=""
  module_parent=""


  #/********** execution section ************/
   getMode uw_mode
   pf "\n selected option is  $work_mode \n\n"
   # case $uw_mode in
   #  "template" | "both"  )
    # it needs to know what to zip so it still has to run some other things
      create_template
   #   ;;
   #   "zip" )
   #    zip_files
   #   ;;
   # esac
   # i need to be able to jump directly to the zip
