CREATE TABLE IF NOT EXISTS `#__psmod` (
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`title` VARCHAR(250) UNIQUE NOT NULL DEFAULT '',
`tool_data` TEXT NOT NULL DEFAULT '',
`options` TEXT NOT NULL DEFAULT '',
`module_id` INT(10) NOT NULL DEFAULT '0',
`data_ids` TEXT NOT NULL DEFAULT '',
PRIMARY KEY (`id`)
 )ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


 CREATE TABLE IF NOT EXISTS `#__psmod_colors` (
 `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
 `title` VARCHAR(250) NOT NULL DEFAULT '',
 `user_id` INT(11) NOT NULL,
 `user_name` VARCHAR(255) NOT NULL,
 `data` TEXT NOT NULL DEFAULT '',
 PRIMARY KEY (`id`)
  )ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

 CREATE TABLE IF NOT EXISTS `#__psmod_assets` (
 `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
 `user_id` INT(11) NOT NULL,
 `init_date` TIMESTAMP NOT NULL,
 `created` BIGINT NOT NULL,
 `modified` BIGINT NOT NULL,
 `title` VARCHAR(250) NOT NULL DEFAULT '',
 `img_data` TEXT NOT NULL DEFAULT '',
 `txt_data` TEXT NOT NULL DEFAULT '',
`params` TEXT NOT NULL DEFAULT '',
 PRIMARY KEY (`id`)
  )ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

  CREATE TABLE IF NOT EXISTS `#__psmod_pages` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `init_date` TIMESTAMP NOT NULL,
  `created` BIGINT NOT NULL,
  `modified` BIGINT NOT NULL,
  `title` VARCHAR(255) UNIQUE NOT NULL DEFAULT '',
  `meta_data` TEXT NOT NULL DEFAULT '',
  `content_data` TEXT NOT NULL DEFAULT '',
  `params` TEXT NOT NULL DEFAULT '',
  `menu_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`menu_id`)
  REFERENCES `#__menu`(`id`)
  ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;



